### ISSUE TITLE
Incomplete Polyfill Shimming on iOS devices

### ISSUE THREAD

**Issue by SamBrishes** [atypiape/polyfill-crypto-methods#1]
Hello,

first of all, thanks for this polyfill. it is indeed really helpful.

However, it does not completely shim the missing functions on iOS devices / Safari Browser 8 - 15.3. Since in these browser versions there is the [crypto global](https://caniuse.com/?search=crypto) available, but contains only a single function (+ `subtle`, at least on Safari 11).

Thus it would be very helpful if you could add the 2 other functions in the same way as you already handle [randomBytes](https://github.com/atypiape/polyfill-crypto-methods/blob/master/lib/polyfill.ts#L14:L16).

```js
if (!("getRandomValues" in globalThat.crypto)) {
  (globalThat.crypto as any).getRandomValues = getRandomValues;
}
if (!("randomBytes" in globalThat.crypto)) {
  (globalThat.crypto as any).randomBytes = randomBytes;
}
if (!("randomUUID" in globalThat.crypto)) {
  (globalThat.crypto as any).randomUUID = randomUUID;
}
```

Thanks.

Sincerely,
Sam.

**Comment by atypiape** [comment]
> Hello,
> 
> first of all, thanks for this polyfill. it is indeed really helpful.
> 
> However, it does not completely shim the missing functions on iOS devices / Safari Browser 8 - 15.3. Since in these browser versions there is the [crypto global](https://caniuse.com/?search=crypto) available, but contains only a single function (+ `subtle`, at least on Safari 11).
> 
> Thus it would be very helpful if you could add the 2 other functions in the same way as you already handle [randomBytes](https://github.com/atypiape/polyfill-crypto-methods/blob/master/lib/polyfill.ts#L14:L16).
> 
> ```js
> if (!("getRandomValues" in globalThat.crypto)) {
>   (globalThat.crypto as any).getRandomValues = getRandomValues;
> }
> if (!("randomBytes" in globalThat.crypto)) {
>   (globalThat.crypto as any).randomBytes = randomBytes;
> }
> if (!("randomUUID" in globalThat.crypto)) {
>   (globalThat.crypto as any).randomUUID = randomUUID;
> }
> ```
> 
> Thanks.
> 
> Sincerely, Sam.

Thank you very much for your advice! I've added the 2 other functions in the same way. But I don't have a test environment, so I don't know if it's correct. It would be great if you could help test it!

**Comment by SamBrishes** [comment]
Hello,

thanks for the update. Works perfectly, tested on an iPhone X using browserstack.

Before:
![image](https://github.com/atypiape/polyfill-crypto-methods/assets/106578633/c8a1b58e-94a0-4a50-85a5-f34c8efc9630)

After:
![image](https://github.com/atypiape/polyfill-crypto-methods/assets/106578633/e30bb858-b689-43fd-85b6-f8696f2b34f3)

~ Sam.

**Comment by atypiape** [comment]
@SamBrishes Thank you very much for your help！
